name: proper use of variables (secrets and environment variables)

on: push

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    name: Staging
    env:
      AWS_REGION: us-east1
      CONTAINER_NAME: nice-app-service
    steps:
      -  name: Check out the code
         uses: actions/checkout@v4
      -  name: configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         #with means it requires previous attributes to work properly
         # do not put all of these "with" variables under ENV, it is dangerous
         # secret keys use secrets, environment variables use varabiles
         # the use of with will allow github to create secure shells and encypt the data, all done 
         # behind the scenes.
         with: 
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
     
